baseURL = "/"
relativeurls = true
languageCode = "en-GB"
title = "My New Hugo Site"
theme = "hugo-tea"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
pygmentsCodeFences = false # If enabled, will conflict with highlight.js

[permalinks]
  post = "/:year/:month/:day/:slug/"

[[menu.main]]
  name = "About"
  url = "/about/"

[author]
	name = "John Smith"
	url = "http://www.example.com"
	
[social]
	facebook 		= ""
  twitter 		= ""
	linkedin 		= ""
  github 			= ""
	googleplus  = ""
	
[params]
	tagline 		= "Just another Hugo site"
  description = "Just another Hugo site"

  # Enable Font Awesome social icons.
  # Go to http://fontawesome.io/get-started/
  # and enter the ".js" URL you are sent in the embed code via e-mail
  fontawesome = ""
  
  # GitHub repository for utteranc.es
  githubRepo = ""

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github-gist"

  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

  [params.logo]
  url = "logo.svg"
	rss = "" # logo for RSS feed
  width = 120
  height = ""
  alt = "Tea and Stats"

  [params.footerimage]
  url = "logo.svg"
  width = 60
  height = ""
