name: Build and upload blogdown site to GitHub

on:
  push:
    branches:
      - source  # where the blog posts source files are written

jobs:
  blogdown:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Install blogdown and R Markdown
        run: Rscript -e "install.packages('blogdown', dependencies = TRUE)"
        
      - name: Install other R packages used in blog posts
        run: Rscript -e "install.packages('ggChernoff')"
        
      - name: Install Hugo
        run: Rscript -e "blogdown::install_hugo()"
        
      - name: Render site
        run: Rscript -e "blogdown::build_site()"
        
      - name: Upload built site files as artifact  
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
    
    checkout-and-deploy:
      runs-on: ubuntu-latest
      needs: blogdown
      steps:
        - name: Checkout source branch
          uses: actions/checkout@v2
          
        - name: Download built site files as artifact
          uses: actions/download-artifact@v2
          with:
            name: public # Artifact name
            path: public # Destination path
            
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
            publish_branch: master
            cname: selbydavid.com
            
