on:
  push:
    branches:
      - source  # where the blog posts source files are written

name: Build and upload blogdown site to GitHub

jobs:
  blogdown:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Query R package dependencies
        run: |
          install.packages(c('remotes', 'sessioninfo'))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE),
                  '.github/depends.Rds', version = 2)
        shell: Rscript {0}
        
      - name: Cache R packages 
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
        
      - name: Install R package dependencies
        run: Rscript -e "remotes::install_deps(dependencies = TRUE)"
        
      - name: Install Hugo
        run: Rscript -e "blogdown::install_hugo('0.79.1')"
        
      - name: Render site
        run: Rscript -e "blogdown::build_site()"
        
      - name: Upload built site files as artifact  
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
          
      - name: R session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, 'Package']
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
          
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: blogdown
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2

      - name: Download built site files as artifact
        uses: actions/download-artifact@v2
        with:
          name: public # Artifact name
          path: public # Destination path

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          cname: selbydavid.com
